### ISSUE TITLE
nginx: [emerg] unknown directive "aws_secret_key" in /nginx.conf:39

### ISSUE THREAD

**Issue by stephanlindauer** [coopernurse/nginx-s3-proxy#2]
currently when i try to run this container, i get: 

```
nginx: [emerg] unknown directive "aws_secret_key" in /nginx.conf:39
```

**Comment by stephanlindauer** [comment]
https://github.com/coopernurse/nginx-s3-proxy/pull/1 solves this issue

**Comment by coopernurse** [comment]
Great, I merged #1 and pushed an updated `coopernurse/nginx-s3-proxy` to docker hub.

Does that fix this for you?  are the `aws_secret_key` config directives still valid, or does the README need to be updated?

**Comment by stephanlindauer** [comment]
yep. with that merged pr, the directives work again as described in the Readme.md
so nothing more to do. thx ;)

**Comment by coopernurse** [comment]
Excellent, thanks for following up.  Closing this ticket.
